language: r
cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true
install:
  - R -e "0" --args --bootstrap-packrat
r_github_packages:
  - jimhester/lintr
sudo: false
